version: "3.3"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CHANNEL_SECRET=${CHANNEL_SECRET}
      - CHANNEL_TOKEN=${CHANNEL_TOKEN}
      - PORT=${PORT}
